# Generated by Django 6.0.6 on 2026-06-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_alter_blogcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_time'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
    ]
