# Generated by Django 6.1a1 on 2026-06-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_alter_captchamodel_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchamodel',
            name='captcha',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
